# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import argument_pb2 as protos_dot_argument__pb2
from protos.plugin import model_pb2 as protos_dot_plugin_dot_model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/command.proto\x12\x07\x63ommand\x1a\x15protos/argument.proto\x1a\x19protos/plugin/model.proto\"r\n\x0c\x43rsInterface\x12&\n\x07\x63ommand\x18\n \x01(\x0b\x32\x13.command.CrsCommandH\x00\x12\x31\n\rcommand_group\x18\x0b \x01(\x0b\x32\x18.command.CrsCommandGroupH\x00\x42\x07\n\x05level\"\xf6\x01\n\nCrsCommand\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x1e\n\x04help\x18\x04 \x01(\x0b\x32\x10.command.CrsHelp\x12\x19\n\x0c\x63onfirmation\x18\x05 \x01(\tH\x01\x88\x01\x01\x12\x1d\n\x04\x61rgs\x18\n \x03(\x0b\x32\x0f.command.CrsArg\x12\x17\n\x0fpositional_args\x18\x0b \x03(\t\x12.\n\x05model\x18\x15 \x01(\x0b\x32\x1d.plugin.CrsPluginModelCommandH\x00\x42\x08\n\x06pluginB\x0f\n\r_confirmation\"\x13\n\x11\x43rsBuildInCommand\"\x9d\x01\n\x0f\x43rsCommandGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x1e\n\x04help\x18\x04 \x01(\x0b\x32\x10.command.CrsHelp\x12(\n\x06groups\x18\n \x03(\x0b\x32\x18.command.CrsCommandGroup\x12%\n\x08\x63ommands\x18\x0b \x03(\x0b\x32\x13.command.CrsCommand\"4\n\x07\x43rsHelp\x12\r\n\x05short\x18\x01 \x01(\t\x12\x11\n\x04long\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_long\"~\n\tCrsParams\x12.\n\x06params\x18\x01 \x03(\x0b\x32\x1e.command.CrsParams.ParamsEntry\x12\x12\n\npatch_keys\x18\x02 \x03(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"F\n\x0f\x43rsOutputFormat\x12\x33\n\x0c\x66latten_mode\x18\x01 \x01(\x0e\x32\x1d.command.CrsOutputFlattenMode*5\n\x14\x43rsOutputFlattenMode\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05\x42\x41SIC\x10\x01\x12\x08\n\x04\x46ULL\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.command_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSPARAMS_PARAMSENTRY._options = None
  _CRSPARAMS_PARAMSENTRY._serialized_options = b'8\001'
  _CRSOUTPUTFLATTENMODE._serialized_start=883
  _CRSOUTPUTFLATTENMODE._serialized_end=936
  _CRSINTERFACE._serialized_start=83
  _CRSINTERFACE._serialized_end=197
  _CRSCOMMAND._serialized_start=200
  _CRSCOMMAND._serialized_end=446
  _CRSBUILDINCOMMAND._serialized_start=448
  _CRSBUILDINCOMMAND._serialized_end=467
  _CRSCOMMANDGROUP._serialized_start=470
  _CRSCOMMANDGROUP._serialized_end=627
  _CRSHELP._serialized_start=629
  _CRSHELP._serialized_end=681
  _CRSPARAMS._serialized_start=683
  _CRSPARAMS._serialized_end=809
  _CRSPARAMS_PARAMSENTRY._serialized_start=764
  _CRSPARAMS_PARAMSENTRY._serialized_end=809
  _CRSOUTPUTFORMAT._serialized_start=811
  _CRSOUTPUTFORMAT._serialized_end=881
# @@protoc_insertion_point(module_scope)
