# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: disable=line-too-long
# pylint: disable=too-many-lines

from azure.cli.core.aaz import *


@register_command_group(
    "network vnet",
    is_experimental=True,
)
class __CMDGroup(AAZCommandGroup):
    """Manage Azure Virtual Networks.

    To learn more about Virtual Networks visit
    https://docs.microsoft.com/azure/virtual-network/virtual-network-manage-network.
    """
    pass


__all__ = ["__CMDGroup"]
