# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

from azure.cli.core.aaz import *


@register_command(
    "network vnet show",
)
class Show(AAZCommand):
    """Get the details of a virtual network.
    """
    pass


__all__ = ["Show"]
