# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/component.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import command_pb2 as protos_dot_command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/component.proto\x12\tcomponent\x1a\x14protos/command.proto\"n\n\x12\x43rsPluginComponent\x12.\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.component.ComponentMetadata\x12(\n\tinterface\x18\x02 \x01(\x0b\x32\x15.command.CrsInterface\"_\n\x11\x43omponentMetadata\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x1e\n\x04help\x18\x04 \x01(\x0b\x32\x10.command.CrsHelpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.component_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSPLUGINCOMPONENT._serialized_start=59
  _CRSPLUGINCOMPONENT._serialized_end=169
  _COMPONENTMETADATA._serialized_start=171
  _COMPONENTMETADATA._serialized_end=266
# @@protoc_insertion_point(module_scope)
