# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/condition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/plugin/condition.proto\x12\x06plugin\"K\n\x0c\x43rsCondition\x12\x0b\n\x03var\x18\x01 \x01(\t\x12.\n\x08operator\x18\x02 \x01(\x0b\x32\x1c.plugin.CrsConditionOperator\"\xe7\x01\n\x14\x43rsConditionOperator\x12.\n\x03\x61nd\x18\x01 \x01(\x0b\x32\x1f.plugin.CrsConditionAndOperatorH\x00\x12,\n\x02or\x18\x02 \x01(\x0b\x32\x1e.plugin.CrsConditionOrOperatorH\x00\x12.\n\x03not\x18\x03 \x01(\x0b\x32\x1f.plugin.CrsConditionNotOperatorH\x00\x12\x39\n\thas_value\x18\x04 \x01(\x0b\x32$.plugin.CrsConditionHasValueOperatorH\x00\x42\x06\n\x04type\"J\n\x17\x43rsConditionAndOperator\x12/\n\toperators\x18\x01 \x03(\x0b\x32\x1c.plugin.CrsConditionOperator\"I\n\x16\x43rsConditionOrOperator\x12/\n\toperators\x18\x01 \x03(\x0b\x32\x1c.plugin.CrsConditionOperator\"I\n\x17\x43rsConditionNotOperator\x12.\n\x08operator\x18\x01 \x01(\x0b\x32\x1c.plugin.CrsConditionOperator\"+\n\x1c\x43rsConditionHasValueOperator\x12\x0b\n\x03\x61rg\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.plugin.condition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSCONDITION._serialized_start=41
  _CRSCONDITION._serialized_end=116
  _CRSCONDITIONOPERATOR._serialized_start=119
  _CRSCONDITIONOPERATOR._serialized_end=350
  _CRSCONDITIONANDOPERATOR._serialized_start=352
  _CRSCONDITIONANDOPERATOR._serialized_end=426
  _CRSCONDITIONOROPERATOR._serialized_start=428
  _CRSCONDITIONOROPERATOR._serialized_end=501
  _CRSCONDITIONNOTOPERATOR._serialized_start=503
  _CRSCONDITIONNOTOPERATOR._serialized_end=576
  _CRSCONDITIONHASVALUEOPERATOR._serialized_start=578
  _CRSCONDITIONHASVALUEOPERATOR._serialized_end=621
# @@protoc_insertion_point(module_scope)
