# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.plugin import resource_pb2 as protos_dot_plugin_dot_resource__pb2
from protos.plugin import condition_pb2 as protos_dot_plugin_dot_condition__pb2
from protos.plugin import selector_pb2 as protos_dot_plugin_dot_selector__pb2
from protos.plugin import operation_pb2 as protos_dot_plugin_dot_operation__pb2
from protos.plugin import output_pb2 as protos_dot_plugin_dot_output__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/plugin/model.proto\x12\x06plugin\x1a\x1cprotos/plugin/resource.proto\x1a\x1dprotos/plugin/condition.proto\x1a\x1cprotos/plugin/selector.proto\x1a\x1dprotos/plugin/operation.proto\x1a\x1aprotos/plugin/output.proto\"\x97\x02\n\x15\x43rsPluginModelCommand\x12*\n\tresources\x18\x01 \x03(\x0b\x32\x17.plugin.CrsRestResource\x12(\n\nconditions\x18\x02 \x03(\x0b\x32\x14.plugin.CrsCondition\x12\x41\n\x14subresource_selector\x18\x03 \x01(\x0b\x32\x1e.plugin.CrsSubresourceSelectorH\x00\x88\x01\x01\x12(\n\noperations\x18\x04 \x03(\x0b\x32\x14.plugin.CrsOperation\x12\"\n\x07outputs\x18\x05 \x03(\x0b\x32\x11.plugin.CrsOutputB\x17\n\x15_subresource_selectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.plugin.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSPLUGINMODELCOMMAND._serialized_start=188
  _CRSPLUGINMODELCOMMAND._serialized_end=467
# @@protoc_insertion_point(module_scope)
