# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/operation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.plugin import http_pb2 as protos_dot_plugin_dot_http__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/plugin/operation.proto\x12\x06plugin\x1a\x18protos/plugin/http.proto\"\x91\x02\n\x0c\x43rsOperation\x12\x12\n\nconditions\x18\x01 \x03(\t\x12(\n\x04http\x18\x02 \x01(\x0b\x32\x18.plugin.CrsHttpOperationH\x00\x12=\n\x0finstance_create\x18\x03 \x01(\x0b\x32\".plugin.CrsInstanceCreateOperationH\x00\x12=\n\x0finstance_update\x18\x04 \x01(\x0b\x32\".plugin.CrsInstanceUpdateOperationH\x00\x12=\n\x0finstance_delete\x18\x05 \x01(\x0b\x32\".plugin.CrsInstanceDeleteOperationH\x00\x42\x06\n\x04type\"\xa0\x01\n\x10\x43rsHttpOperation\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12%\n\x06\x61\x63tion\x18\x02 \x01(\x0b\x32\x15.plugin.CrsHttpAction\x12>\n\x0clong_running\x18\x03 \x01(\x0b\x32#.plugin.CrsHttpOperationLongRunningH\x00\x88\x01\x01\x42\x0f\n\r_long_running\"\xa8\x01\n\x1b\x43rsHttpOperationLongRunning\x12\x45\n\x0f\x66inal_state_via\x18\x01 \x01(\x0e\x32,.plugin.CrsHttpOperationLongRunning.StateVia\"B\n\x08StateVia\x12\x17\n\x13\x61zureAsyncOperation\x10\x00\x12\x0c\n\x08location\x10\x01\x12\x0f\n\x0boriginalUri\x10\x02\"V\n\x1a\x43rsInstanceCreateOperation\x12\x38\n\x0finstance_create\x18\x01 \x01(\x0b\x32\x1f.plugin.CrsInstanceCreateAction\"V\n\x1a\x43rsInstanceUpdateOperation\x12\x38\n\x0finstance_update\x18\x01 \x01(\x0b\x32\x1f.plugin.CrsInstanceUpdateAction\"V\n\x1a\x43rsInstanceDeleteOperation\x12\x38\n\x0finstance_delete\x18\x01 \x01(\x0b\x32\x1f.plugin.CrsInstanceDeleteAction\"V\n\x17\x43rsInstanceCreateAction\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12&\n\x04json\x18\x02 \x01(\x0b\x32\x16.plugin.CrsRequestJsonH\x00\x42\x06\n\x04type\"V\n\x17\x43rsInstanceUpdateAction\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12&\n\x04json\x18\x02 \x01(\x0b\x32\x16.plugin.CrsRequestJsonH\x00\x42\x06\n\x04type\"V\n\x17\x43rsInstanceDeleteAction\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12&\n\x04json\x18\x02 \x01(\x0b\x32\x16.plugin.CrsRequestJsonH\x00\x42\x06\n\x04typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.plugin.operation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSOPERATION._serialized_start=68
  _CRSOPERATION._serialized_end=341
  _CRSHTTPOPERATION._serialized_start=344
  _CRSHTTPOPERATION._serialized_end=504
  _CRSHTTPOPERATIONLONGRUNNING._serialized_start=507
  _CRSHTTPOPERATIONLONGRUNNING._serialized_end=675
  _CRSHTTPOPERATIONLONGRUNNING_STATEVIA._serialized_start=609
  _CRSHTTPOPERATIONLONGRUNNING_STATEVIA._serialized_end=675
  _CRSINSTANCECREATEOPERATION._serialized_start=677
  _CRSINSTANCECREATEOPERATION._serialized_end=763
  _CRSINSTANCEUPDATEOPERATION._serialized_start=765
  _CRSINSTANCEUPDATEOPERATION._serialized_end=851
  _CRSINSTANCEDELETEOPERATION._serialized_start=853
  _CRSINSTANCEDELETEOPERATION._serialized_end=939
  _CRSINSTANCECREATEACTION._serialized_start=941
  _CRSINSTANCECREATEACTION._serialized_end=1027
  _CRSINSTANCEUPDATEACTION._serialized_start=1029
  _CRSINSTANCEUPDATEACTION._serialized_end=1115
  _CRSINSTANCEDELETEACTION._serialized_start=1117
  _CRSINSTANCEDELETEACTION._serialized_end=1203
# @@protoc_insertion_point(module_scope)
