# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/output.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/plugin/output.proto\x12\x06plugin\"\x92\x01\n\tCrsOutput\x12)\n\x06object\x18\x01 \x01(\x0b\x32\x17.plugin.CrsObjectOutputH\x00\x12\'\n\x05\x61rray\x18\x02 \x01(\x0b\x32\x16.plugin.CrsArrayOutputH\x00\x12)\n\x06string\x18\x03 \x01(\x0b\x32\x17.plugin.CrsStringOutputH\x00\x42\x06\n\x04type\"6\n\x0f\x43rsObjectOutput\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_flatten\x18\x02 \x01(\x08\"[\n\x0e\x43rsArrayOutput\x12\x0b\n\x03ref\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_flatten\x18\x02 \x01(\x08\x12\x16\n\tnext_link\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_next_link\"9\n\x0f\x43rsStringOutput\x12\r\n\x03ref\x18\x01 \x01(\tH\x00\x12\x0f\n\x05value\x18\x02 \x01(\tH\x00\x42\x06\n\x04typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.plugin.output_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSOUTPUT._serialized_start=39
  _CRSOUTPUT._serialized_end=185
  _CRSOBJECTOUTPUT._serialized_start=187
  _CRSOBJECTOUTPUT._serialized_end=241
  _CRSARRAYOUTPUT._serialized_start=243
  _CRSARRAYOUTPUT._serialized_end=334
  _CRSSTRINGOUTPUT._serialized_start=336
  _CRSSTRINGOUTPUT._serialized_end=393
# @@protoc_insertion_point(module_scope)
