# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/selector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.plugin import schema_pb2 as protos_dot_plugin_dot_schema__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/plugin/selector.proto\x12\x06plugin\x1a\x1aprotos/plugin/schema.proto\"d\n\x16\x43rsSubresourceSelector\x12\x0b\n\x03var\x18\x01 \x01(\t\x12\x0b\n\x03ref\x18\x02 \x01(\t\x12(\n\x04json\x18\x03 \x01(\x0b\x32\x18.plugin.CrsSelectorIndexH\x00\x42\x06\n\x04type\"$\n\x14\x43rsSelectorIndexInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xd0\x01\n\x10\x43rsSelectorIndex\x12/\n\x04info\x18\x01 \x01(\x0b\x32\x1c.plugin.CrsSelectorIndexInfoH\x01\x88\x01\x01\x12(\n\x06object\x18\x02 \x01(\x0b\x32\x16.plugin.CrsObjectIndexH\x00\x12&\n\x05\x61rray\x18\x03 \x01(\x0b\x32\x15.plugin.CrsArrayIndexH\x00\x12(\n\x06simple\x18\x04 \x01(\x0b\x32\x16.plugin.CrsSimpleIndexH\x00\x42\x06\n\x04typeB\x07\n\x05_info\"\xc7\x01\n\x1b\x43rsObjectIndexDiscriminator\x12\x10\n\x08property\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12+\n\x04prop\x18\x03 \x01(\x0b\x32\x18.plugin.CrsSelectorIndexH\x00\x88\x01\x01\x12?\n\rdiscriminator\x18\x04 \x01(\x0b\x32#.plugin.CrsObjectIndexDiscriminatorH\x01\x88\x01\x01\x42\x07\n\x05_propB\x10\n\x0e_discriminator\"t\n\"CrsObjectIndexAdditionalProperties\x12&\n\x04item\x18\x01 \x01(\x0b\x32\x18.plugin.CrsSelectorIndex\x12&\n\x0bidentifiers\x18\x02 \x03(\x0b\x32\x11.plugin.CrsSchema\"\xf9\x01\n\x0e\x43rsObjectIndex\x12+\n\x04prop\x18\x01 \x01(\x0b\x32\x18.plugin.CrsSelectorIndexH\x00\x88\x01\x01\x12?\n\rdiscriminator\x18\x02 \x01(\x0b\x32#.plugin.CrsObjectIndexDiscriminatorH\x01\x88\x01\x01\x12I\n\x10\x61\x64\x64itional_props\x18\x03 \x01(\x0b\x32*.plugin.CrsObjectIndexAdditionalPropertiesH\x02\x88\x01\x01\x42\x07\n\x05_propB\x10\n\x0e_discriminatorB\x13\n\x11_additional_props\"m\n\rCrsArrayIndex\x12+\n\x04item\x18\x01 \x01(\x0b\x32\x18.plugin.CrsSelectorIndexH\x00\x88\x01\x01\x12&\n\x0bidentifiers\x18\x02 \x03(\x0b\x32\x11.plugin.CrsSchemaB\x07\n\x05_item\"\x10\n\x0e\x43rsSimpleIndexb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.plugin.selector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CRSSUBRESOURCESELECTOR._serialized_start=68
  _CRSSUBRESOURCESELECTOR._serialized_end=168
  _CRSSELECTORINDEXINFO._serialized_start=170
  _CRSSELECTORINDEXINFO._serialized_end=206
  _CRSSELECTORINDEX._serialized_start=209
  _CRSSELECTORINDEX._serialized_end=417
  _CRSOBJECTINDEXDISCRIMINATOR._serialized_start=420
  _CRSOBJECTINDEXDISCRIMINATOR._serialized_end=619
  _CRSOBJECTINDEXADDITIONALPROPERTIES._serialized_start=621
  _CRSOBJECTINDEXADDITIONALPROPERTIES._serialized_end=737
  _CRSOBJECTINDEX._serialized_start=740
  _CRSOBJECTINDEX._serialized_end=989
  _CRSARRAYINDEX._serialized_start=991
  _CRSARRAYINDEX._serialized_end=1100
  _CRSSIMPLEINDEX._serialized_start=1102
  _CRSSIMPLEINDEX._serialized_end=1118
# @@protoc_insertion_point(module_scope)
