syntax = "proto3";
package command;

import "protos/argument.proto";
import "protos/plugin/model.proto";

// The interface of the command / command group / component
message CrsInterface {
  oneof level {
    CrsCommand command = 10;
    CrsCommandGroup command_group = 11;
  }
}

message CrsCommand {
  string name = 1;
  string uri = 2; // the uri of the command / command group / component, the uri should be unique across all the commands, command groups and components
  string version = 3; // the version of the command
  CrsHelp help = 4;
  optional string confirmation = 5;  // support to prompt for command confirmation
  repeated CrsArg args = 10;
  repeated string positional_args = 11;  // the array of positional argument names
  oneof plugin {
    plugin.CrsPluginModelCommand model = 21;
  }
}

message CrsBuildInCommand {}

message CrsCommandGroup {
  string name = 1;
  string uri = 2; // the uri of the command / command group / component, the uri should be unique across all the commands, command groups and components
  CrsHelp help = 4;
  repeated CrsCommandGroup groups = 10;
  repeated CrsCommand commands = 11;
}

message CrsHelp {
  string short = 1; // short description of the command
  optional string long = 2;  // long description of the command
}

message CrsParams {
  map<string, bytes> params = 1;
  // the keys of the params which are assigned as patch value, the value
  // can be `param1.prop1[1].tags.a` or `param1.prop1+`. Here the `+`
  // means to extend the array properties.
  repeated string patch_keys = 2;
}

// CrsOutputFlattenMode indicates the flatten mode of the output
enum CrsOutputFlattenMode {
  NONE = 0;    // return the output without any flatten applied
  BASIC = 1;   // return the output with basic flatten applied (usually apply the x-ms-client-flatten definition in the swagger)
  FULL = 2;    // return the output with fully flatten applied (the fully flatten mode will be used for table like output such as the PowerShell output)
}

message CrsOutputFormat {
  CrsOutputFlattenMode flatten_mode = 1; // the flatten mode of the output
}