name: Python Compatibility Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - resilv/py313

env:
  # Change this to invalidate existing cache.
  CACHE_PREFIX: v0
  PYTHON_PATH: ./

permissions:
  contents: read

jobs:
  checks:
    name: Python ${{ matrix.python }} - ${{ matrix.os }} - ${{ matrix.task.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]  # Original - temporarily testing Windows only
        os: [windows-latest]
        python: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        task:
          - name: Build
            run: |
              set -x
              pip list
              pip install twine
              # update setup related tools
              pip install --upgrade setuptools wheel
              pip list
              python setup.py check
              python setup.py bdist_wheel sdist
              # check package metadata
              twine check ./dist/*

#          - name: Test
#            run: |
#              pytest -v --color=yes tests/

#          - name: Lint
#            run: flake8 .

#          - name: Type check
#            run: mypy .

#          - name: Style
#            run: black --check .

#          - name: Docs
#            run: cd docs && make html

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: ${{ runner.os != 'Windows' && 'recursive' || 'false' }}
      
      - name: Configure Git for long paths (Windows)
        if: runner.os == 'Windows'
        run: |
          git config --system core.longpaths true
          git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install prerequisites
        run: |
          pip install --upgrade pip setuptools wheel virtualenv
          npm install -g pnpm@9.5.0
          pnpm install

      - name: Set build variables
        shell: bash
        run: |
          # Get the exact Python version to use in the cache key.
          echo "PYTHON_VERSION=$(python --version)" >> $GITHUB_ENV
          echo "RUNNER_ARCH=$(uname -m)" >> $GITHUB_ENV
          echo "NODE_VERSION=$(node --version)" >> $GITHUB_ENV
          # Use week number in cache key so we can refresh the cache weekly.
          echo "WEEK_NUMBER=$(date +%V)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        id: virtualenv-cache
        with:
          path: |
            .venv
          key: ${{ env.CACHE_PREFIX }}-${{ env.WEEK_NUMBER }}-${{ runner.os }}-${{ env.RUNNER_ARCH }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.CACHE_PREFIX }}-${{ env.WEEK_NUMBER }}-${{ runner.os }}-${{ env.RUNNER_ARCH }}-${{ env.PYTHON_VERSION }}

      - name: Setup virtual environment (no cache hit)
        if: steps.virtualenv-cache.outputs.cache-hit != 'true'
        run: |
          test -d .venv || virtualenv -p $(which python) --copies --reset-app-data .venv
          . .venv/bin/activate
          pip install -e .[dev]

      - name: Install editable (cache hit)
        if: steps.virtualenv-cache.outputs.cache-hit == 'true'
        run: |
          . .venv/bin/activate
          pip install --no-deps -e .[dev]

      - name: Show environment info
        run: |
          . .venv/bin/activate
          which python
          python --version
          pip freeze
          which node
          node --version
          npm --version
          pnpm --version

      - name: Build Web
        run: |
          pnpm build:typespec
          pnpm build:web
          pnpm bundle
        env:
          CI: false
      - name: Test Typespec-aaz Emitter
        run: |
            pnpm test-aaz-emitter

      - name: ${{ matrix.task.name }}
        run: |
          . .venv/bin/activate
          ${{ matrix.task.run }}

      - name: Clean up
        if: always()
        run: |
          . .venv/bin/activate
          pip uninstall -y my-package
